apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: camunda
  name: camunda-int-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: camunda

