apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: default
spec:
  selector:
    spilo-role: master
    statefulset.kubernetes.io/pod-name: vehres-dbclust-camunda-0
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  type: ClusterIP

