apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: camunda
  name: camunda
spec:
  replicas: 1
  selector:
    matchLabels:
      run: camunda

  template:
    metadata:
      labels:
        run: camunda
    spec:
      containers:
      - image: camunda/camunda-bpm-platform:latest
        name: camunda
        ports:
        - containerPort: 8080

        env:
          - name: DB_DRIVER
            value: "org.postgresql.Driver"
          - name: DB_URL
            value: "jdbc:postgresql://postgres-svc:5432/camunda"
          - name: DB_USERNAME
            value: "postgres"
          - name: DB_PASSWORD
            value: "jP29jplWRIB0dQiKkB0HAgo3rK869mG57rDaPrwxtOhy5gBn1V0pW6FyFpFqJLSo"
          - name: PGSSLMODE
            value: require

